os: osx
osx_image: xcode13.0
language: objective-c

cache:
  directories:
    - $HOME/.cocoapods

before_install:
  - set -x
  - gem install cocoapods
  - pod repo update > /dev/null

script: 
  - ./travis_build.sh
