require_relative '../OpenTokSDKVersion'

platform :ios, '13'
use_frameworks!

target 'Video-Transformers' do
 pod 'OTXCFramework', OpenTokSDKVersion
 pod 'VonageClientSDKVideoTransformers', OpenTokSDKVersion
end
