platform :ios, '9.0'
use_frameworks!

require_relative '../OpenTokSDKVersion'

target 'Basic-Video-Chat' do
  pod 'OpenTok', OpenTokSDKVersion
end

target 'OpenTok Live' do
  pod 'OpenTok', OpenTokSDKVersion
end
