require_relative '../OpenTokSDKVersion'

platform :ios, MinIosSdkVersion
use_frameworks!

target 'Broadcast-Ext' do
    target 'OpenTok Live' do
        pod 'OTXCFramework', OpenTokSDKVersion
    end
end
