#!/bin/bash -xe

SVG_BRANCH=master
SVG_DIR=quicksvg
if [ ! -d $SVG_DIR ]; then
(
    git clone https://github.com/opentable/QuickSVG $SVG_DIR
    cd $SVG_DIR; git checkout $SVG_BRANCH; git pull
)
else
(
    cd $SVG_DIR
    git checkout $SVG_BRANCH; git pull
)
fi


