require_relative '../OpenTokSDKVersion'

platform :ios, MinIosSdkVersion
use_frameworks!

target 'Camera-Controls' do
 pod 'OTXCFramework', OpenTokSDKVersion
 pod 'VonageClientSDKVideoTransformers', OpenTokSDKVersion
end
